### ISSUE TITLE
option to retrieve additional metadata in jsonrecords format

### ISSUE THREAD

**Issue by jspeis** [jazzido/mondrian-rest#23]
If I have a dimension `Foo` with a hierarchy like `Parent Group` > `Child Group` and I do a drilldown on `Foo` by `Child Group` in `jsonrecords`style, would be great if I could add a flag to tell mondrian-rest that I would like to also retrieve available metadata (e.g. name of the `Parent Group`). 

This would be useful for example in the context of data visualizations where I want to drilldown to the deepest child level but group by the parent.

**Comment by jazzido** [comment]
I got you, brother. It's been there since the beggining: https://github.com/jazzido/mondrian-rest/blob/d58d8db562480054ae8aac834797388615a873ae/spec/api_spec.rb#L174-L183

Just add `parents=true` to your query string. This is [also exposed in `mondrian-rest-client`](https://github.com/jazzido/mondrian-rest/blob/d58d8db562480054ae8aac834797388615a873ae/spec/api_spec.rb#L174-L183): `.option('parents', true)`.

**Comment by jazzido** [comment]
(…yeah, we need better documentation).

**Comment by jspeis** [comment]
woot! thanks
